handler: lambdas/hello-world/index.handler
name: hello-world
# customize as needed to connect your lambda function to layers
layers:
  - { Ref: ApiLayerLambdaLayer }
package:
  include:
    - lambdas/hello-world/index.js
    - lambdas/hello-world/node_modules/**
events:
  - http:
      method: get
      path: hello
      cors: true
