service:
  name: template-kaskadi-api

plugins:
  - serverless-aws-documentation

custom:
  documentation:
    api:
      info:
        version: 0.0.1
        title: ${self:service.name}
        description: Template API

provider:
  name: aws
  runtime: nodejs10.x
  stackName: ${self:service.name}-stack
  stage: ${opt:stage, 'prod'}
  region: eu-central-1
  deploymentBucket:
    name: 'kaskadi-serverless-deployment-bucket'

functions:
  ${file(./lambdas/hello-world/serverless.yml)}
